// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "golang-crud-ddd/domain"

	mock "github.com/stretchr/testify/mock"
)

// IRefreshTokensRepo is an autogenerated mock type for the IRefreshTokensRepo type
type IRefreshTokensRepo struct {
	mock.Mock
}

// GetRefreshTokens provides a mock function with given fields: token
func (_m *IRefreshTokensRepo) GetRefreshTokens(token string) (*domain.RefreshTokens, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokens")
	}

	var r0 *domain.RefreshTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.RefreshTokens, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.RefreshTokens); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeRefreshTokens provides a mock function with given fields: token
func (_m *IRefreshTokensRepo) RevokeRefreshTokens(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRefreshTokens provides a mock function with given fields: data
func (_m *IRefreshTokensRepo) SaveRefreshTokens(data *domain.RefreshTokens) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.RefreshTokens) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRefreshTokensRepo creates a new instance of IRefreshTokensRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRefreshTokensRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRefreshTokensRepo {
	mock := &IRefreshTokensRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
