name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1  # pin for stability

      - name: Show Make version
        run: make --version

      - name: Lint
        run: make lint

      - name: Test
        run: make test
